//! Generate the evidence and effect registries from `definitions/atoms.yaml`.
//!
//! The atoms file is the one place a name is defined (87, 138); the registry is
//! its shape in Rust and is never written by hand. The generated module records
//! the hash of the file it was generated from, so a name added to the file
//! without a regeneration is caught rather than silently missing.

use serde::Deserialize;
use std::collections::BTreeMap;
use std::path::PathBuf;

#[derive(Deserialize)]
struct AtomsFile {
    evidence: BTreeMap<String, EvidenceEntry>,
    effects: BTreeMap<String, EffectEntry>,
}

// The atoms file writes its entries as YAML flow mappings whose `doc:` text may
// itself hold commas, so a doc splits into keys no schema names. Unknown keys
// are therefore ignored rather than refused: `of`, `type`, `proof`, `proof_of`,
// `args`, `values` and `satisfies` are the fields the registry carries.
#[derive(Deserialize)]
struct EvidenceEntry {
    #[serde(default)]
    of: serde_yaml::Value,
    #[serde(rename = "type")]
    ty: String,
    #[serde(default)]
    values: Vec<String>,
    #[serde(default)]
    proof_of: Option<String>,
}

#[derive(Deserialize)]
struct EffectEntry {
    #[serde(default)]
    of: serde_yaml::Value,
    #[serde(default)]
    args: Vec<String>,
    proof: String,
    #[serde(default)]
    satisfies: Vec<u32>,
}

fn owners(v: &serde_yaml::Value) -> Vec<String> {
    match v {
        serde_yaml::Value::String(s) => vec![s.clone()],
        serde_yaml::Value::Sequence(a) => {
            a.iter().filter_map(|x| x.as_str().map(String::from)).collect()
        }
        _ => vec![],
    }
}

/// FNV-1a over the file's bytes. The registry is data, not a secret; all this
/// has to do is move when a byte does, and it must be reproducible from the
/// test without a dependency.
fn fnv1a(bytes: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in bytes {
        h ^= *b as u64;
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    h
}

fn strings(items: &[String]) -> String {
    let inner: Vec<String> = items.iter().map(|s| format!("{s:?}")).collect();
    format!("&[{}]", inner.join(", "))
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let atoms = manifest.join("../../definitions/atoms.yaml");
    println!("cargo:rerun-if-changed={}", atoms.display());
    println!("cargo:rerun-if-changed=build.rs");

    let bytes = std::fs::read(&atoms)
        .unwrap_or_else(|e| panic!("definitions/atoms.yaml is not readable: {e}"));
    let file: AtomsFile = serde_yaml::from_slice(&bytes)
        .unwrap_or_else(|e| panic!("definitions/atoms.yaml does not parse: {e}"));

    let mut out = String::new();
    out.push_str("// Generated by build.rs from definitions/atoms.yaml. Do not edit.\n");
    out.push_str(&format!(
        "pub const ATOMS_FILE_HASH: u64 = {:#x};\n",
        fnv1a(&bytes)
    ));

    out.push_str("pub static EVIDENCE: &[EvidenceAtom] = &[\n");
    for (name, e) in &file.evidence {
        // An evidence whose type the file does not name is a file error, not a
        // registry with a hole in it.
        let ty = match e.ty.as_str() {
            "bool" => "AtomType::Bool",
            "int" => "AtomType::Int",
            "string" => "AtomType::String",
            "time" => "AtomType::Time",
            "list" => "AtomType::List",
            "state" => "AtomType::State",
            "enum" => "AtomType::Enum",
            "hash" => "AtomType::Hash",
            "host-id" => "AtomType::HostId",
            other => panic!("atoms.yaml: evidence {name} has unknown type {other}"),
        };
        let proof_of = match &e.proof_of {
            Some(p) => format!("Some({p:?})"),
            None => "None".to_string(),
        };
        out.push_str(&format!(
            "    EvidenceAtom {{ name: {:?}, of: {}, ty: {}, values: {}, proof_of: {} }},\n",
            name,
            strings(&owners(&e.of)),
            ty,
            strings(&e.values),
            proof_of
        ));
    }
    out.push_str("];\n");

    out.push_str("pub static EFFECTS: &[EffectAtom] = &[\n");
    for (name, f) in &file.effects {
        let satisfies: Vec<String> = f.satisfies.iter().map(|n| n.to_string()).collect();
        out.push_str(&format!(
            "    EffectAtom {{ name: {:?}, of: {}, args: {}, proof: {:?}, satisfies: &[{}] }},\n",
            name,
            strings(&owners(&f.of)),
            strings(&f.args),
            f.proof,
            satisfies.join(", ")
        ));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("atoms_generated.rs");
    std::fs::write(dest, out).unwrap();
}
